version: '3.8'

networks:
  backnet:
  frontnet:

services:

  # This is the proxy which receives all http requests and forwards to relevant servers.
  proxy:
    image: nginx:mainline-alpine
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - webserver
      - apiserver
    networks:
      - frontnet
      - backnet
    volumes:
      - ./shared-files/proxy-nginx.conf:/etc/nginx/nginx.conf
      - ./localhost.crt:/etc/nginx/cert.crt # replace with real certificate
      - ./localhost.key:/etc/nginx/key.key # replace with real key
    restart: on-failure:5

  # Web server hosts the static files
  webserver:
    image: lmsdoubtfire/doubtfire-web:prod-6
    ports:
      - 8080:8080
    networks:
      - backnet
    restart: on-failure:5

  # API server runs the rails project
  apiserver:
    image: lmsdoubtfire/apiserver:prod-6
    env_file:
      - .env.production
    ports:
      - 3000:3000
    networks:
      - backnet
    depends_on:
      - doubtfire-db
    volumes:
      - student_work:/student-work # Adjust path to where student data should be stored
      - doubtfire_logs:/doubtfire/log
      - ./shared-files:/shared-files
      - ./shared-files/aliases:/etc/aliases:ro
    command: /bin/bash -c "rm -f /doubtfire/tmp/pids/server.pid; bundle exec rails s -b 0.0.0.0"
    restart: on-failure:5

  # Database server - could be external to docker
  doubtfire-db:
    image: mariadb:10
    restart: always
    networks:
      - backnet
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_USER: dfire # Update with mariadb username
      MARIADB_PASSWORD: pwd # Update with mariadb password
      MARIADB_DATABASE: doubtfire # Update with mariadb database name
    volumes:
      - mysql_db:/var/lib/mysql

  # Automated generation of PDFs using cron
  pdfgen:
    image: lmsdoubtfire/appserver:prod-6
    env_file:
      - .env.production
    networks:
      - backnet
    depends_on:
      - doubtfire-db
    volumes:
      - student_work:/student-work # Update with path to student work
      - ./shared-files:/shared-files
      - ./shared-files/aliases:/etc/aliases:ro
      - doubtfire_logs:/doubtfire/log
    command:
      /bin/bash -c "newaliases; cp /shared-files/msmtprc /etc; /doubtfire/entry_point.sh"
    restart: on-failure:5

volumes:
  doubtfire_logs: {}
  mysql_db: {}
  student_work: {}

